models:
  simple:
    input_size: 25
    output_size: 2
    hidden_size: 512
    hidden_count: 5
    lr: 0.00005
    epochs: 5
  xgboost:
    n_estimators: 1000
    max_depth: 10
    random_state: 1

config:
  input_loc: input/

data:
  train:
    filename: norm_train.csv
    batch_size: 4
  test:
    filename: norm_test.csv
    batch_size: 16

