models:
  simple:
    input_size: 25
    output_size: 1
    hidden_size: 50
    hidden_count: 2
    lr: 0.001
    epochs: 2
  xgboost:
    n_estimators: 1000
    max_depth: 10
    random_state: 1

config:
  input_loc: input/

data:
  train:
    filename: norm_train.csv
    batch_size: 4
  test:
    filename: norm_test.csv
    batch_size: 1
